# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartEvm', '0002_auto_20170408_0605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Party',
            new_name='Party_Name',
        ),
    ]
