# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartEvm', '0003_auto_20170408_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashes',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashes',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
