# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartEvm', '0004_auto_20170415_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashes',
            field=models.CharField(max_length=2700, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashes',
            field=models.CharField(max_length=2700, unique=True),
        ),
    ]
